version: '2'
services:
  oracle_db:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1521:1521"
    container_name: oracle_db_container
    volumes:
      - D:/oracle_db:/data
    environment:
      - ORACLE_SID=FREE
      - ORACLE_PWD=mysecretpassword
    networks:
      - mynetwork
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    volumes:
      - D:/zookeeper:/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - mynetwork
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    volumes:
      - D:/kafka:/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - mynetwork

networks:
  mynetwork: